creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - "age1x2xcu8ml8yrwyhk466mkq7rc0cux39anawcgr4gstee7pl83j9cqzdwt8l"
          - "age157r8ngcus3jngrhjsv4nk4dsmj34vdk2ynq0457vqylguk4tlqcsq26fx2"
